### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ufechner7** [ufechner7/KiteViewer#1]
- [x] Merge and release the singlewindow branch
- [ ] Add a script to import the "TU Delft Kitepower data"
- [ ] Add receiver for UDP packages as interface to Simulink or other systems/ models
- [x] Add tether model
- [x] Add winch model -> in package WinchModels.jl
- [x] Add one-point kite model
- [x] Add four-point kite model -> in package KiteModels.jl
- [x] Add model of Kite Control Unit (KCU)
- [x] Add real-time simulator (RTSim)
- [x] Add flight controller

**Comment by ufechner7** [comment]
The development of controllers happens in the package https://github.com/aenarete/KiteControllers.jl
